IF
Global("D#SilverSummoned","GLOBAL",0)
IfValidForPartyDialogue("D#Silver")
THEN
RESPONSE #100
SetGlobal("D#SilverSummoned","GLOBAL",2)
Continue()
END

IF
Global("D#SilverSummoned","GLOBAL",1)
Global("D#SilverSpawnPlane","GLOBAL",0)
THEN
RESPONSE #100
CreateVisualEffect("SPPORTAL",[1999.1218])
Wait(2)
MoveGlobal("AR4500","D#Silver",[1999.1218])
ActionOverride("D#Silver",SetDialog("D#Silve1"))
SetGlobal("D#SilverSpawnPlane","GLOBAL",1)
END

